// food.dart

class FoodItems {
  static final List<Map<String, dynamic>> foodList = [
    {
      "name": "Apple",
      "carbs": 25,
      "protein": 0.3,
      "fats": 0.2,
      "vitamins": "Vitamin C",
      "calories": 95,
      "deficiency": "None",
    },
    {
      "name": "Banana",
      "carbs": 27,
      "protein": 1.3,
      "fats": 0.4,
      "vitamins": "Vitamin B6, Vitamin C",
      "calories": 105,
      "deficiency": "None",
    },
    {
      "name": "Chicken Breast",
      "carbs": 0,
      "protein": 31,
      "fats": 3.6,
      "vitamins": "Vitamin B6, Vitamin B12",
      "calories": 165,
      "deficiency": "None",
    },
    {
      "name": "Salmon",
      "carbs": 0,
      "protein": 25,
      "fats": 13,
      "vitamins": "Vitamin D, Vitamin B12",
      "calories": 208,
      "deficiency": "None",
    },
    {
      "name": "Broccoli",
      "carbs": 6,
      "protein": 2.8,
      "fats": 0.4,
      "vitamins": "Vitamin C, Vitamin K",
      "calories": 55,
      "deficiency": "None",
    },
    {
      "name": "Quinoa",
      "carbs": 21,
      "protein": 4.4,
      "fats": 1.9,
      "vitamins": "Magnesium, Iron",
      "calories": 120,
      "deficiency": "None",
    },
    {
      "name": "Almonds",
      "carbs": 6,
      "protein": 6,
      "fats": 14,
      "vitamins": "Vitamin E, Magnesium",
      "calories": 164,
      "deficiency": "None",
    },
    {
      "name": "Eggs",
      "carbs": 0.6,
      "protein": 6,
      "fats": 5,
      "vitamins": "Vitamin B12, Vitamin D",
      "calories": 68,
      "deficiency": "None",
    },
    {
      "name": "Avocado",
      "carbs": 9,
      "protein": 2,
      "fats": 15,
      "vitamins": "Vitamin K, Vitamin E",
      "calories": 160,
      "deficiency": "None",
    },
    {
      "name": "Spinach",
      "carbs": 1,
      "protein": 0.9,
      "fats": 0.1,
      "vitamins": "Vitamin A, Vitamin C",
      "calories": 7,
      "deficiency": "None",
    },
    {
      "name": "Sweet Potato",
      "carbs": 20,
      "protein": 1.6,
      "fats": 0.1,
      "vitamins": "Vitamin A, Vitamin C",
      "calories": 90,
      "deficiency": "None",
    },
    {
      "name": "Oats",
      "carbs": 12,
      "protein": 2.5,
      "fats": 1.5,
      "vitamins": "Magnesium, Iron",
      "calories": 68,
      "deficiency": "None",
    },
    {
      "name": "Greek Yogurt",
      "carbs": 4,
      "protein": 10,
      "fats": 0.4,
      "vitamins": "Calcium, Vitamin B12",
      "calories": 59,
      "deficiency": "None",
    },
    {
      "name": "Dark Chocolate",
      "carbs": 13,
      "protein": 2,
      "fats": 12,
      "vitamins": "Iron, Magnesium",
      "calories": 170,
      "deficiency": "None",
    },
    {
      "name": "Lentils",
      "carbs": 20,
      "protein": 9,
      "fats": 0.4,
      "vitamins": "Iron, Folate",
      "calories": 116,
      "deficiency": "None",
    },
  ];
}